name: br
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: D3Hunter/tidb
          ref: change-flag-name
      - name: Setup tag
        run: |
          git tag v6.2.0-alpha
      - name: Set docker sha
        run: |
          echo "DOCKER_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: make build_br
      - name: Create Dockerfile
        run: |
          cat > Dockerfile.br <<EOF 
          FROM ubuntu:22.04
          COPY ./bin/br /br
          ENTRYPOINT ["/br"]
          EOF
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: gozssky/br
          tags: |
            type=raw,value=v{{date 'YYYYMMDD'}}-${{ env.DOCKER_SHA }}
            type=raw,value=latest
      # The v2 version of docker/build-push-action uses Docker Buildx to build.
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.br
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Image digest
        run:
          echo ${{ steps.docker_build.outputs.digest }}
